version: '{build}'
skip_tags: true

environment:
  AUTH_TOKEN:
    secure: EQ9miMjfX/QAoBvgc6D+JLmHatLyxOEKZ/uo68QijxWW5Gp4MzB/pOH9+u2GlDVO

configuration: Release

build: 
    project: update.sln
    parallel: true

after_build:
  
  - cd Win32
  - 7z a ../Update.zip ./* -xr!.git* -mx9
  - cd ..

test: off

artifacts:
  - path: Update.zip
    name: Update
