version: '{build}'
skip_tags: true

environment:
  AUTH_TOKEN:
    secure: EQ9miMjfX/QAoBvgc6D+JLmHatLyxOEKZ/uo68QijxWW5Gp4MzB/pOH9+u2GlDVO

configuration: Release

build: 
    project: update.sln
    parallel: true

after_build: 
  - cp -rf Win32/update.exe .


test: off

artifacts:
  - path: update.exe
    name: Update
