version: '{build}'
skip_tags: true

environment:
  AUTH_TOKEN:
    secure: EQ9miMjfX/QAoBvgc6D+JLmHatLyxOEKZ/uo68QijxWW5Gp4MzB/pOH9+u2GlDVO

configuration: Release

build: 
    project: update.sln
    parallel: true

after_build:
  - git config --global user.name "Smile-DK"
  - git config --global user.email "2236141431@qq.com"
  
  - git clone --depth=1 https://github.com/purerosefallen/ygopro-222DIY-data
  
  - cp -rf Win32/update.exe data/update
  - cd data
  - git add . -A
  - git commit -m "Build Update"
  - git push https://%AUTH_TOKEN%@github.com/purerosefallen/ygopro-222DIY master
  
  - cd ../Win32
  - 7z a ../Update.zip ./* -xr!.git* -mx9
  - cd ..

test: off

artifacts:
  - path: Update.zip
    name: Update

branches:
  only:
    - master
